INSERT INTO PRODUCT(NAME, DESCRIPTION, PRICE, ADDED) VALUES('Rx-8', 'Mouse for laptop', 35.89, LOCALTIMESTAMP(0));
INSERT INTO PRODUCT(NAME, DESCRIPTION, PRICE, ADDED) VALUES('HP 15', 'Laptop', 335.00, LOCALTIMESTAMP(0));
INSERT INTO ACCOUNT(FIRSTNAME, LASTNAME, EMAIL, CREATED)
VALUES('Mihhail', 'Mat', 'mih@gmail.com', LOCALTIMESTAMP(0));
INSERT INTO CREDITCARD(NUMBER, HOLDER, EXP_YEAR, EXP_MONTH, ACCOUNT_ID)
VALUES('1111222233334444', 'Mihhail Mat', 2020, 12, 1);